---
title: "regresion_lineal"
author: "CARLOS ALEX NINA GUARDAPUCLLA"
date: "2023-04-22"
output: html_document
---

# REGRESION LINEAL SIMPLE

## IMPORTAR LIBRERIAS

```{r}
install.packages("tidyverse")
```


```{r}
library(caTools)
library(tidyverse)
library(dbplyr)
```


```{r}
# Leer el archivo CSV
df <- read.csv("C:/Users/Alex/Desktop/R/machine learning/0.data/Salary_Data.csv")

# Mostrar los datos
head(df)
```

## Dividir el conjunto de entrenamiento
```{r}
set.seed(123)
split = sample.split(df$Salary, SplitRatio = 2/3)
training_set = subset(df, split==TRUE)
testing_set = subset(df, split==FALSE)
```

## Escalado de valores
```{r}
#training_set[,2:3] = scale(training_set[,2:3])
#testing_set[,2:3] = scale(testing_set[,2:3])
```


## crear el modeo de regresion lineal
```{r}
# (var_dependiente ~ vars_independientes)
model = lm(formula = Salary ~ YearsExperience,
           data = training_set)
```

```{r}
summary(model)
```

## predecir resultados con vel modelo entrenado
```{r}
y_pred <- predict(model, newdata = testing_set) 
print(y_pred)
```

## visualizacion de resultados
```{r}
library(ggplot2)
```

```{r}
# TRAINING VS PREDICT_TRAINING
ggplot() +
  geom_point(aes(x = training_set$YearsExperience, y = training_set$Salary), colour = "red") +
  geom_line(aes(x = training_set$YearsExperience, y = predict(model, newdata = training_set)), colour = "blue")+

ggtitle("Sueldo vs A単os de experiencia conjunto de training")+
  xlab("A単os de experiencia")+
  ylab("sueldo en dolares")
```

```{r}
# TEST VS PREDICT_TEST
ggplot() +
  geom_point(aes(x = testing_set$YearsExperience, y = testing_set$Salary), colour = "red") +
  geom_line(aes(x = testing_set$YearsExperience, y = predict(model, newdata = testing_set)), colour = "blue")+

ggtitle("Sueldo vs A単os de experiencia conjunto de testing")+
  xlab("A単os de experiencia")+
  ylab("sueldo en dolares")
```












































